language: ruby
rvm:
- ruby-head

before_script:
 - chmod +x ./script/build.sh
 - npm install --global surge

script: ./script/build.sh

branches:
  only:
  - master

after_success:
   surge -p ./_site/
