language: ruby
rvm:
- 2.3.0

before_script:
 - chmod +x ./script/cibuild
 - npm install --global surge
 - npm install
 - npm run gulp

script: ./script/cibuild

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false

after_success:
   surge -p ./_site/
