language: ruby
rvm:
- 2.3.0

before_script:
 - chmod +x ./script/cibuild
 - npm install --global surge
 - npm install

script: ./script/cibuild

branches:
  only:
  - master

sudo: false

after_success:
   surge -p ./_site/
