title: John Jarana
email: alan.boglioli@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  MetaDescription
baseurl: "/demo" # the subpath of your site, e.g. /blog
url: "http://barramovilmendoza.com.ar" # the base hostname & protocol for your site, e.g. http://example.com
assets: "/demo/assets" # Include baseurl
images: "/demo/assets/images"

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - docs
  - dist
